### PR TITLE
Enhancement/add image comparison

### LINKED ISSUE #318: Is it possible to compare screenshots with this project?
Playwright Test includes the ability to produce and visually compare screenshots using `expect(value).toMatchSnapshot(snapshotName)`. More information on this article: [Visual comparisons | Playwright](https://playwright.dev/docs/test-snapshots).

Since Cucumber replaces Playwright Test in this project, is there an alternative way to do this? Do you have plans on supporting these Playwright Test additional functions?

Best wishes,
Priscila.

### PR DESCRIPTION
**Pull request by ortsevlised**
**Added a step to compare screenshot to a base image using pixelmatch**

- It can be use as:

` 'the screen matches the base image'`
` 'the screen matches the base image with timeout of {number}'` optional time out in case the page is not stable before the screenshot

- The difference threshold can be adjusted on the config file via IMG_THRESHOLD
- The base image is taken under the path `/screenshots/{feature_name}/{OS}/{browser}/{test_name}.png`
- Make sure you commit your base image otherwise the test will fail. 
_Please note that the screenshots might vary according to the browser and OS where they are running, so make sure you upload the right image._

Resolves #318

### CODE REVIEW

**Comment by Tallyb** [comment]
That is amazing. 
However, I am not sure how this works when people create a branch that has some changes? They should run and commit the file? can you add this to the PR?

**Comment by ortsevlised** [comment]
You mean, you want me to add a better comment explaining how it should be used, or you are asking me to commit the base image?

**Comment by Tallyb** [comment]
@ortsevlised  - maybe both?

**Comment by ortsevlised** [comment]
Done!

**Comment by Tallyb** [comment]
@ortsevlised   I have added this step with some changes. However, I could not run it, as the image has major differences (I ran it on local docker to generate linux image). You can download the report from here: https://github.com/Tallyb/cucumber-playwright/actions/runs/1872026515
Any idea why this is so?

**Comment by ortsevlised** [comment]
> @ortsevlised I have added this step with some changes. However, I could not run it, as the image has major differences (I ran it on local docker to generate linux image). You can download the report from here: https://github.com/Tallyb/cucumber-playwright/actions/runs/1872026515 Any idea why this is so?

Hi, all I can think of is that the your local docker might have a different os/browser version than what github action is using, so you might have minor differences.

When I tested I had the image generated in github actions and then uploaded it to the repo and that worked. However that image now is outdated as the homepage changed a bit (for example the version number it's now 1.19).

My suggestion are: 
- modify the code to to take the screenshot and add it as part of the artifacts in github action so you then can take it and upload it to the repository.
- Delete the base image and add a 'retry' for the tests that need an image, so the first run creates the images and the second one finishes the test.

**Pull request closed without merging**
